name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      run: |
        npm install -g firebase-tools
        
    - name: Build and optimize
      run: |
        # 清理不需要的文件
        rm -f deployment-guide.md
        rm -f .firebaserc
        rm -f firebase.json
        rm -f firestore.indexes.json
        rm -f firestore.rules
        rm -f storage.rules
        rm -f config.json
        
        # 保留必要的文件
        echo "Building optimized version..."
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: '.github,functions,node_modules'
        
    - name: Deploy Firebase Rules
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        # 先檢出原始檔案
        git checkout HEAD -- firebase.json firestore.rules storage.rules firestore.indexes.json
        
        # 部署 Firebase 規則
        firebase deploy --only firestore:rules,storage:rules,firestore:indexes --token "$FIREBASE_TOKEN" 